language: go
go: 1.x

sudo: false

before_install: go get github.com/mitchellh/gox
install: /bin/true

script:
  - go get -t -v ./...
  - gox -os="linux windows" -arch="386 amd64" -verbose ./...

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: sjX4qkm5N1+VNDeUz2hTlq9caO7Ch0mOT0EV/ytfE5WHcySQ78GVaclttwQk05sNUkGYPKl2hjZpaf5WAtKKwCw0vFsBvxNvroGom66cvc4TFR8wUJNODSabxmfuKBlhjaTmfKZxf9XYQ7k68X/93Kbq/JGKCA+Vf/9Ngm1olfrN5cBXqK57v7G516PwKvYqMpi5VVnJi7h34SHK/cHLTO4HJy0HIt7laEJyPFFHl+/Od234Gq06/0+yeFdUjFqbEOwt/3T6RetcMcuWdBEyLBUrJkpRoz5rsUCCIDoCvJ648l4HaHCPzDPFW0xrbUD+XuCIBdCDLkIHgCRbbo0cKQJJUwjveEduOpLIe+CZLVhL1NnADfadWrYF3Z4ErYMfI2Yevnz7BTiZ7u+WP9T/9bHg00Z1fXUqDZiwrx35G4TnYa4+Gt833GOsa+loYhKLj5FO3CFepE/EL+KF6yrzEVolShuXj9b3bDS9hb4pbrmOK2cPFl8XsTd0Sh1ryRwP+EN/Sj8kalEPWOsT6SMeKTcDwGZrZ+RSqirVXikNedx+6xs1/+L0RKWNb3TzeaTemQ5EGeGuVOda7nnbJKpvpqYB3qJYL10FQBfRXwXirmcpNN1+AkQGl2uJ7hpabfnxiOgICtDW5WFD93djIEoBmYvc6fD1xb9ZEy2csrGjMH4=
  file:
    - "eu4autosave_windows_386.exe"
    - "eu4autosave_windows_amd64.exe"
    - "eu4autosave_linux_386"
    - "eu4autosave_linux_amd64"
  on:
    repo: s5i/eu4tool
    tags: true