name: Autorelease eu4autosave

on:
  push:
    tags:
      - 'eu4autosave-v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.3'

      - name: Fetch dependencies
        run: go get -u github.com/s5i/eu4tool/eu4autosave

      - name: Fetch Gox
        run: go install github.com/mitchellh/gox@latest

      - name: Build
        run: gox -osarch="linux/386 linux/amd64 windows/386 windows/amd64 darwin/amd64" -verbose ./...

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset (eu4autosave_windows_386.exe)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./eu4autosave_windows_386.exe
          asset_name: eu4autosave_windows_386.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (eu4autosave_windows_amd64.exe)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./eu4autosave_windows_amd64.exe
          asset_name: eu4autosave_windows_amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (eu4autosave_linux_386)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./eu4autosave_linux_386
          asset_name: eu4autosave_linux_386
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (eu4autosave_linux_amd64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./eu4autosave_linux_amd64
          asset_name: eu4autosave_linux_amd64
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (eu4autosave_darwin_amd64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./eu4autosave_darwin_amd64
          asset_name: eu4autosave_darwin_amd64
          asset_content_type: application/octet-stream
